import 'package:intl/intl.dart';
import '../models/category.dart';
import '../models/expense.dart';
import '../models/budget.dart';
import '../models/app_settings.dart';
import '../utils/financial_period.dart';
import 'category_classifier.dart';
import 'financial_calculation_engine.dart';
import 'storage_service.dart';

/// Confidence level of an AI categorization suggestion.
enum AiConfidence {
  high,
  medium,
  low,
}

/// A structured categorization result from the AI engine.
class AiCategorySuggestion {
  final String expenseId;
  final String merchant;
  final Category category;
  final AiConfidence confidence;
  final String rationale;

  const AiCategorySuggestion({
    required this.expenseId,
    required this.merchant,
    required this.category,
    required this.confidence,
    required this.rationale,
  });
}

/// Type of insight generated by the AI Financial Advisor.
enum AiInsightType {
  criticalWarning,
  budgetPacing,
  smartSavings,
  trendAlert,
  positiveMilestone,
}

/// Actionable AI financial recommendation.
class AiRecommendation {
  final String title;
  final String message;
  final AiInsightType type;
  final Category? relatedCategory;
  final double? impactAmount;

  const AiRecommendation({
    required this.title,
    required this.message,
    required this.type,
    this.relatedCategory,
    this.impactAmount,
  });
}

/// Comprehensive AI financial review bundle.
class AiFinancialReview {
  final HealthScoreReport healthReport;
  final PacingAnalysis pacing;
  final List<AiRecommendation> recommendations;
  final Map<Category, double> categoryDistribution;
  final double totalSpend;
  final double burnRateMultiplier;

  const AiFinancialReview({
    required this.healthReport,
    required this.pacing,
    required this.recommendations,
    required this.categoryDistribution,
    required this.totalSpend,
    required this.burnRateMultiplier,
  });
}

/// On-device, privacy-preserving AI engine for financial analysis and classification.
class AiFinancialAdvisorService {
  const AiFinancialAdvisorService._();

  /// Batch auto-categorizes a list of pending/uncategorized expenses.
  ///
  /// Combines learned merchant memory, semantic keyword classifiers,
  /// recurring transaction history, and title heuristics.
  static List<AiCategorySuggestion> categorizePendingExpenses({
    required List<Expense> expenses,
    required StorageService storageService,
  }) {
    final suggestions = <AiCategorySuggestion>[];

    for (final exp in expenses) {
      final title = exp.title.trim();
      if (title.isEmpty) continue;

      // 1. Check learned merchant memory first (highest confidence)
      final memoryLookup = storageService.lookupMerchantCategory(title);
      if (memoryLookup != null) {
        suggestions.add(
          AiCategorySuggestion(
            expenseId: exp.id,
            merchant: title,
            category: memoryLookup,
            confidence: AiConfidence.high,
            rationale: 'Learned from your previous transaction history',
          ),
        );
        continue;
      }

      // 2. Pass through unified CategoryClassifier
      final classification = CategoryClassifier.classify(title);
      if (classification.category != Category.other) {
        final isExact = classification.isConfident;
        suggestions.add(
          AiCategorySuggestion(
            expenseId: exp.id,
            merchant: classification.normalizedMerchant.isNotEmpty
                ? classification.normalizedMerchant
                : title,
            category: classification.category,
            confidence: isExact ? AiConfidence.high : AiConfidence.medium,
            rationale: 'Matched merchant signature "${classification.category.displayName}"',
          ),
        );
        continue;
      }

      // 3. Amount & title pattern heuristics
      final lowerTitle = title.toLowerCase();
      if (lowerTitle.contains('pay') || lowerTitle.contains('transfer') || lowerTitle.contains('upi')) {
        suggestions.add(
          AiCategorySuggestion(
            expenseId: exp.id,
            merchant: title,
            category: Category.other,
            confidence: AiConfidence.low,
            rationale: 'General transfer detected. Confirm category',
          ),
        );
      } else {
        suggestions.add(
          AiCategorySuggestion(
            expenseId: exp.id,
            merchant: title,
            category: Category.other,
            confidence: AiConfidence.low,
            rationale: 'New merchant pattern',
          ),
        );
      }
    }

    return suggestions;
  }

  /// Synthesizes an intelligent financial review from active transactions and settings.
  static AiFinancialReview generateReview({
    required List<Expense> allExpenses,
    required List<Budget> budgets,
    required AppSettings settings,
    DateTime? referenceDate,
  }) {
    final now = referenceDate ?? DateTime.now();
    final period = FinancialPeriod.containing(now, settings.startingDayOfMonth);

    final currentCycleExpenses = allExpenses
        .where((e) => !e.isUncategorized && period.contains(e.date))
        .toList();

    final totalCurrentSpend = currentCycleExpenses.fold(0.0, (sum, e) => sum + e.amount);

    // Category distribution
    final catSums = <Category, double>{};
    for (final e in currentCycleExpenses) {
      catSums[e.category] = (catSums[e.category] ?? 0.0) + e.amount;
    }

    // Pacing
    final pacing = FinancialCalculationEngine.calculatePacing(
      spendSoFar: totalCurrentSpend,
      budget: settings.monthlyBudget,
      daysElapsed: period.daysElapsed(now),
      totalDays: period.totalDays,
    );

    // Approximate recurring total
    final recurringTotal = _estimateRecurringTotal(allExpenses);

    // Health Score
    final health = FinancialCalculationEngine.evaluateHealthScore(
      currentSpend: totalCurrentSpend,
      budget: settings.monthlyBudget,
      recurringTotal: recurringTotal,
      categorySpends: catSums.map((k, v) => MapEntry(k.name, v)),
      daysElapsed: period.daysElapsed(now),
      totalDays: period.totalDays,
    );

    final recommendations = <AiRecommendation>[];
    final currency = settings.currency;
    final money = NumberFormat('#,##0');

    // Recommendation 1: Budget Pacing Alert
    if (settings.monthlyBudget > 0) {
      if (pacing.status == PacingStatus.overBudget) {
        recommendations.add(
          AiRecommendation(
            title: 'Overspending Velocity Detected',
            message:
                'You are on pace to spend $currency${money.format(pacing.projectedMonthEnd)} by end of cycle ($currency${money.format(pacing.deltaFromBudget.abs())} above budget). Cap daily spending at $currency${money.format(pacing.dailySafeToSpend)}.',
            type: AiInsightType.criticalWarning,
            impactAmount: pacing.deltaFromBudget.abs(),
          ),
        );
      } else if (pacing.status == PacingStatus.caution) {
        recommendations.add(
          AiRecommendation(
            title: 'Spending Running Warm',
            message:
                'Your current burn rate is ${(pacing.burnRate * 100).toStringAsFixed(0)}% of your target allowance. Recommended daily ceiling: $currency${money.format(pacing.dailySafeToSpend)}.',
            type: AiInsightType.budgetPacing,
          ),
        );
      } else {
        recommendations.add(
          AiRecommendation(
            title: 'Budget On Track',
            message:
                'Excellent discipline! Pacing is ${(pacing.burnRate * 100).toStringAsFixed(0)}% of target. Projected cycle savings: $currency${money.format(pacing.deltaFromBudget)}.',
            type: AiInsightType.positiveMilestone,
            impactAmount: pacing.deltaFromBudget,
          ),
        );
      }
    }

    // Recommendation 2: Dominant Category Insight
    if (catSums.isNotEmpty && totalCurrentSpend > 0) {
      final topCategoryEntry = catSums.entries.reduce((a, b) => a.value > b.value ? a : b);
      final pct = (topCategoryEntry.value / totalCurrentSpend) * 100;
      if (pct > 35) {
        recommendations.add(
          AiRecommendation(
            title: '${topCategoryEntry.key.displayName} Spending Surge',
            message:
                '${topCategoryEntry.key.displayName} accounts for ${pct.toStringAsFixed(0)}% of your total spend ($currency${money.format(topCategoryEntry.value)}).',
            type: AiInsightType.trendAlert,
            relatedCategory: topCategoryEntry.key,
            impactAmount: topCategoryEntry.value,
          ),
        );
      }
    }

    // Recommendation 3: Category Budget Limits Check
    for (final b in budgets) {
      if (b.monthlyLimit > 0) {
        final spent = catSums[b.category] ?? 0.0;
        final ratio = spent / b.monthlyLimit;
        if (ratio >= 0.90) {
          recommendations.add(
            AiRecommendation(
              title: '${b.category.displayName} Budget Near Limit',
              message:
                  'You have reached ${(ratio * 100).toStringAsFixed(0)}% of your ${b.category.displayName} budget. $currency${money.format(b.monthlyLimit - spent)} remaining.',
              type: ratio >= 1.0 ? AiInsightType.criticalWarning : AiInsightType.trendAlert,
              relatedCategory: b.category,
            ),
          );
        }
      }
    }

    // Recommendation 4: Actionable Advice from Health Engine
    for (final rec in health.actionableRecommendations) {
      recommendations.add(
        AiRecommendation(
          title: 'Optimization Opportunity',
          message: rec,
          type: AiInsightType.smartSavings,
        ),
      );
    }

    return AiFinancialReview(
      healthReport: health,
      pacing: pacing,
      recommendations: recommendations,
      categoryDistribution: catSums,
      totalSpend: totalCurrentSpend,
      burnRateMultiplier: pacing.burnRate,
    );
  }

  /// Answers natural-language financial queries offline.
  static String answerSpendingQuery({
    required String query,
    required List<Expense> expenses,
    required AppSettings settings,
  }) {
    final cleanQuery = query.toLowerCase().trim();
    final cur = settings.currency;
    final money = NumberFormat('#,##0.##');

    // 1. Query highest / biggest expense
    if (cleanQuery.contains('highest') || cleanQuery.contains('biggest') || cleanQuery.contains('most expensive')) {
      if (expenses.isEmpty) return 'No expenses found in your records.';
      final highest = expenses.reduce((a, b) => a.amount > b.amount ? a : b);
      return 'Your largest single expense is "${highest.title}" for $cur${money.format(highest.amount)} on ${DateFormat('MMM dd, yyyy').format(highest.date)}.';
    }

    // 2. Query category specific
    for (final cat in Category.values) {
      if (cleanQuery.contains(cat.name.toLowerCase()) || cleanQuery.contains(cat.displayName.toLowerCase())) {
        final catExpenses = expenses.where((e) => e.category == cat).toList();
        final catTotal = catExpenses.fold(0.0, (a, b) => a + b.amount);
        return 'You have spent $cur${money.format(catTotal)} on ${cat.displayName} across ${catExpenses.length} transactions.';
      }
    }

    // 3. Query total spending
    if (cleanQuery.contains('total') || cleanQuery.contains('overall') || cleanQuery.contains('how much did i spend')) {
      final total = expenses.fold(0.0, (a, b) => a + b.amount);
      return 'Your total recorded spending is $cur${money.format(total)} across ${expenses.length} transactions.';
    }

    // 4. Default intelligent fallback
    final recent = expenses.take(3).map((e) => '"${e.title}" ($cur${money.format(e.amount)})').join(', ');
    return 'Recent activity: $recent. Ask about specific categories like Food, Bills, Shopping, or your largest expense!';
  }

  static double _estimateRecurringTotal(List<Expense> expenses) {
    final titleCount = <String, int>{};
    final titleSum = <String, double>{};

    for (final e in expenses) {
      final key = e.title.toLowerCase().trim();
      titleCount[key] = (titleCount[key] ?? 0) + 1;
      titleSum[key] = (titleSum[key] ?? 0.0) + e.amount;
    }

    double total = 0.0;
    titleCount.forEach((title, count) {
      if (count >= 2) {
        total += (titleSum[title]! / count);
      }
    });

    return total;
  }
}
